//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/userId
Content-Type: application/json

{
  "_id": "64183c47619efac49ed746fb"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "username": "Emilia M",
  "email": "massing@mail.com",
  "password": "slipknot"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "massing@mail.com",
  "password": "slipknot"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/641d9c802b6a3b39549537fb

###

//Egen temporär router - Hämta enbart produkter i lager
GET http://localhost:3000/api/products/inStock

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "title": "Lightsaber",
  "description": "Out of order",
  "price": 5000, 
  "stock": 0
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "64183c47619efac49ed746fb",
      "products": [
    {
      "productId": "641c71440a16905d20276737",
      "quantity": 1
    },
    {
      "productId": "641d9b342b6a3b39549537f1",
      "quantity": 3
    }
  ]
}

###

// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###